# Generated by Django 6.0.5 on 2026-05-23 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employeedata',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=255)),
                ('emp_mail', models.EmailField(max_length=55)),
                ('emp_address', models.CharField(max_length=255)),
                ('emp_join_date', models.DateTimeField()),
                ('emp_leave_date', models.DateTimeField()),
                ('emp_gender', models.CharField(max_length=255)),
                ('emp_age', models.EmailField(max_length=55)),
            ],
        ),
    ]
